#!/bin/bash
if [ "$(id -u)" != "0" ]; then
    echo "This script requires root acces. Try: sudo discordo"
    exit 1
fi

if ! command -v dpkg &> /dev/null; then
    echo "This OS is not debian based."
    exit 1
fi
echo "Downloading newest version of Discord..."
wget -O /tmp/discord.deb "https://discord.com/api/download?platform=linux&format=deb"
clear
if [ $? -ne 0 ]; then
    echo "Download error."
    exit 1
fi
echo "Installing latest version of Discord..."
dpkg -i /tmp/discord.deb
echo "Done! You now have latest Discord version!"
rm -f /tmp/discord.deb
exit 0
